version: 2.1

jobs:
  hello:
    docker:
      - image: python:3
    steps:
      - checkout
      - run:
          name: Say hello
          command: |
            echo "Hello world"
  test-ssh:
    docker:
      - image: python:3
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints: ["d7:16:77:25:3e:fc:b5:a2:3e:84:c3:15:2e:07:71:ac"]
      - run:
          name: Install dependencies
          command: |
            apt-get update
            apt-get install -y ansible
      - run:
          name: "Run ansible"
          command: |
            echo $(ls)
            # ansible-playbook -i inventory.txt main.yml

workflows:
  default:
    jobs:
      - hello
